//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesboyLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGA
    {
        public string lga_name { get; set; }
        public string lgaid { get; set; }
        public string stateid { get; set; }
    
        public virtual State State { get; set; }
    }
}
