//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesboyMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EasyOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EasyOrder()
        {
            this.EasyOrdersItems = new HashSet<EasyOrdersItem>();
        }
    
        public string id { get; set; }
        public string description { get; set; }
        public string address { get; set; }
        public string loc_long { get; set; }
        public string loc_lat { get; set; }
        public string location { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public string insertuser { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EasyOrdersItem> EasyOrdersItems { get; set; }
    }
}
