//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesboyMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public string id { get; set; }
        public string userid { get; set; }
        public string email { get; set; }
        public string productid { get; set; }
        public string productname { get; set; }
        public string description { get; set; }
        public Nullable<decimal> amountpaid { get; set; }
        public int qty { get; set; }
        public decimal unitprice { get; set; }
        public decimal totalcost { get; set; }
        public int discountperc { get; set; }
        public decimal discountamount { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public string orderid { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
