//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesboyServiceProviders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.Sales = new HashSet<Sale>();
        }
    
        public string id { get; set; }
        public string vendorid { get; set; }
        public string productname { get; set; }
        public string producttype { get; set; }
        public string description { get; set; }
        public string bgphoto { get; set; }
        public string photo1 { get; set; }
        public string photo2 { get; set; }
        public string photo3 { get; set; }
        public string photo4 { get; set; }
        public string photo5 { get; set; }
        public string photo6 { get; set; }
        public string category { get; set; }
        public string tags { get; set; }
        public string size1 { get; set; }
        public string size2 { get; set; }
        public string size3 { get; set; }
        public string size4 { get; set; }
        public string color1 { get; set; }
        public string color2 { get; set; }
        public string color3 { get; set; }
        public string color4 { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> discount { get; set; }
        public string status { get; set; }
        public int qty { get; set; }
        public Nullable<System.DateTime> inserdate { get; set; }
        public string modelno { get; set; }
        public string brandname { get; set; }
        public string otherfeatures { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
