//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesboyServiceProviders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingPayment
    {
        public string id { get; set; }
        public string name { get; set; }
        public string orderid { get; set; }
        public string shipperemail { get; set; }
        public string customerid { get; set; }
        public string shipperid { get; set; }
        public string phone { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> trnxdate { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public string gatewayref { get; set; }
        public string paymenttype { get; set; }
        public string category { get; set; }
        public string title { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Shipper Shipper { get; set; }
    }
}
