//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesboyNigeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public string id { get; set; }
        public string userid { get; set; }
        public string useremail { get; set; }
        public string userip { get; set; }
        public string usermacaddress { get; set; }
        public string productid { get; set; }
        public Nullable<int> qty { get; set; }
        public string size { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual Product Product { get; set; }
    }
}
