//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesboyNigeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EasyOrdersItem
    {
        public string id { get; set; }
        public string orderid { get; set; }
        public string item { get; set; }
        public string amount { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public string insertuser { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
    
        public virtual EasyOrder EasyOrder { get; set; }
    }
}
